export const LOAD_CHAMBRE = "LOAD_CHAMBRE";
export const FAIL_CHAMBRE = "FAIL_CHAMBRE";
export const GET_CHAMBRES_LOAD="GET_CHAMBRES_LOAD";
export const GET_CHAMBRES_SUCCESS="GET_CHAMBRES_SUCCESS";
export const GET_CHAMBRES_FAILED="GET_CHAMBRES_FAILED";
export const DELETE_CHAMBRE= "DELETE_CHAMBRE";
export const EDIT_CHAMBRE="EDIT_CHAMBRE";
export const GET_CHAMBRE="GET_CHAMBRE";
