export const LOAD_CHAUFFEURE = "LOAD_CHAUFFEURE";
export const FAIL_CHAUFFEURE = "FAIL_CHAUFFEURE";
export const GET_CHAUFFEURES_LOAD="GET_CHAUFFEURES_LOAD";
export const GET_CHAUFFEURES_SUCCESS="GET_CHAUFFEURES_SUCCESS";
export const GET_CHAUFFEURES_FAILED="GET_CHAUFFEURES_FAILED";
export const DELETE_CHAUFFEURE= "DELETE_CHAUFFEURE";
export const EDIT_CHAUFFEURE="EDIT_CHAUFFEURE";
export const GET_CHAUFFEURE="GET_CHAUFFEURE";

