export const LOAD_CIRCUIT = "LOAD_CIRCUIT";
export const FAIL_CIRCUIT = "FAIL_CIRCUIT";
export const GET_CIRCUITS_LOAD="GET_CIRCUITS_LOAD";
export const GET_CIRCUITS_SUCCESS="GET_CIRCUITS_SUCCESS";
export const GET_CIRCUITS_FAILED="GET_CIRCUITS_FAILED";
export const DELETE_CIRCUIT= "DELETE_CIRCUIT";
export const EDIT_CIRCUIT="EDIT_CIRCUIT";
export const GET_CIRCUIT="GET_CIRCUIT";


