export const LOAD_FACTURATION = "LOAD_FACTURATION";
export const GET_FACTURATIONS_LOAD = "FAIL_CHAUFFEUREFACTURATION_CHAUFFEURES_LOAD";
export const GET_FACTURATIONS_SUCCESS="GET_FACTURATIONS_SUCCESS";
export const GET_FACTURATIONS_FAILED="GET_FACTURATIONS_FAILED";
export const DELETE_FACTURATION= "DELETE_FACTURATION";
export const EDIT_FACTURATION="EDIT_FACTURATION";
export const GET_FACTURATION="GET_FACTURATION";

