export const LOAD_GOUVERNERANT = "LOAD_GOUVERNERANT";
export const FAIL_GOUVERNERANT = "FAIL_GOUVERNERANT";
export const GET_GOUVERNERANTS_LOAD="GET_GOUVERNERANTS_LOAD";
export const GET_GOUVERNERANTS_SUCCESS="GET_GOUVERNERANTS_SUCCESS";
export const GET_GOUVERNERANTS_FAILED="GET_GOUVERNERANTS_FAILED";
export const DELETE_GOUVERNERANT= "DELETE_GOUVERNERANT";
export const EDIT_GOUVERNERANT="EDIT_GOUVERNERANT";
export const GET_GOUVERNERANT="GET_GOUVERNERANT";
