export const LOAD_HOTEL = "LOAD_HOTEL";
export const FAIL_HOTEL = "FAIL_HOTEL";
export const GET_HOTELS_LOAD="GET_HOTELS_LOAD";
export const GET_HOTELS_SUCCESS="GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAILED="GET_HOTELS_FAILED";
export const DELETE_HOTEL= "DELETE_HOTEL";
export const EDIT_HOTEL="EDIT_HOTEL";
export const GET_HOTEL="GET_HOTEL";
